/*******************************************************************************
* File Name: Swd_PacketLayer.h
* Version 3.0 plus WiringPi modifications
*
* Description:
*  This header file contains the constant definitions, function declarations
*  associated with the packet layer of the SWD protocol. 
*
* Note:
* 
*******************************************************************************/

#ifndef __SWD_PACKETLAYER_H
#define __SWD_PACKETLAYER_H

/********************************************************************************
*   Constant definitions
********************************************************************************/

#define DATA_BYTES_PER_PACKET   4    /* Data size of a SWD Packet in bytes */

/* Number of dummy SWDCK clocks at end of each SWD packet.
   Required for bit banging programmers where clock is not free running  */
#define NUMBER_OF_DUMMY_SWD_CLOCK_CYCLES    3 

#define NUMBER_OF_SWD_RESET_CLOCK_CYCLES    51 /* Minimum number of SWDCK clock cycles to reset the SWD line state */

#define NUMBER_OF_ACK_BITS  3 /* ACK response in a SWD packet is a 3-bit value */

/* SWD ACK response meanings.
*  Parity error definition is not part of SWD ACK response from target.
*  The actual ACK response is only 3-bit length. The parity error bit is defined as fourth bit by host application.
*  It is generated by host if there is a parity error in the SWD Read packet data from target */ 
#define SWD_OK_ACK          0x01
#define SWD_WAIT_ACK        0x02
#define SWD_FAULT_ACK       0x04
#define SWD_PARITY_ERROR    0x08

/* Maximum SWD packet loop timeout for SWD_WAIT_ACK response */
#define NUMBER_OF_WAIT_ACK_LOOPS    5  

#define MSB_BIT_MASK 0x80    /* Mask value to define Most significant bit (MSb) in a Byte */
#define LSB_BIT_MASK 0x01    /* Mask value to define Least significant bit (LSb) in a Byte */

/********************************************************************************
*   Global Variable declaration
********************************************************************************/
/* The below global variables are accessed by the upper layer files to create SWD packet header, ACK, data */
extern unsigned char Swd_packetHeader; 
extern unsigned char Swd_packetAck;    
extern unsigned char Swd_packetData[DATA_BYTES_PER_PACKET];

/********************************************************************************
*   Function Prototypes
********************************************************************************/
/* The below public fuctions are called by the upper layer files to send SWD packets */
void Swd_WritePacket(void);
void Swd_WritePacketFast(unsigned char dataParityBit);
void Swd_RawReadPacket(void);
void Swd_ReadPacket(void);

void JtagToSwdSequence(void);

#endif
